function Create_Mask(prefix, makefile, n_cores, series_sql, MD_parameter, MC_parameter)

    path(path, '/mnt/data/scratch/igilab/jslin1/Matlab_add-ons/mksqlite-1.14')
    path(path, '/mnt/data/scratch/igilab/jslin1/Matlab_add-ons/NIfTI_20140122')
    path(path, '/mnt/data/scratch/igilab/jslin1/RadPath/Functions')
    script01_prefix = 'Script01_T1_T2_SWAN/';
    script02_prefix = 'Script02_DWI_DTI/';
    script03_prefix = 'Script03_DCE_DSC/';
    script04_prefix = 'Script04_VOI/';
    LPBA40_Template_location= '/mnt/data/scratch/igilab/jslin1/LPBA40_Template.nii.gz';
    LPBA40_mask_location = '/mnt/data/scratch/igilab/jslin1/LPBA40_mask.nii.gz';
    mksqlite('open', 'ctkDICOM.sql' );


fid = fopen([prefix  makefile],'w');
fprintf(fid, 'all:');
for ii=1:size(series_sql,1)
    fprintf(fid, [' job' num2str(ii)]);
end
fprintf(fid, '\nANTSPATH=/opt/apps/ANTsR/dev//ANTsR_src/ANTsR/src/ANTS/ANTS-build//bin\n');

for ii=1:size(series_sql,1)
    fprintf(fid,['\n\njob' num2str(ii) ':\n']);
    [ptno Descrip UID ptno_Descrip_UID] = Generate_Label(series_sql(ii));

    % 1. Perform rough down-sampled registration as beginning step to help initialize later registration
    fprintf(fid,['\n\njob' num2str(ii) ':\n']);
    fprintf(fid,['\t$(ANTSPATH)/ResampleImageBySpacing 3 '...
 		LPBA40_Template_location ' '...
		prefix '05_Mask_RInput/Affine_Fixed_LPBA40.nii.gz 4 4 4 1\n']);
    fprintf(fid,['\t$(ANTSPATH)/ResampleImageBySpacing 3 '...
		prefix '01_N4/N4_' ptno_Descrip_UID '.nii.gz '...
		prefix '05_Mask_RInput/Affine_Moving_' ptno_Descrip_UID '.nii.gz 4 4 4 1\n']);
    fprintf(fid,['\t$(ANTSPATH)/antsAffineInitializer 3 '...
		prefix '05_Mask_RInput/Affine_Fixed_LPBA40.nii.gz '...
		prefix '05_Mask_RInput/Affine_Moving_' ptno_Descrip_UID '.nii.gz '...
	        prefix '05_Mask_RInput/InitialAffine_' ptno_Descrip_UID '.mat 15 0.1 0 10\n']);

    % 2. Create Laplacian (edge detection) version of images to assist in registration
    fprintf(fid,['\t$(ANTSPATH)/ImageMath 3 '...
		prefix '05_Mask_RInput/Laplacian_' ptno_Descrip_UID '.nii.gz '...
		'Laplacian '...
		prefix '01_N4/N4_' ptno_Descrip_UID '.nii.gz 1.5 1\n']);
    fprintf(fid,['\t$(ANTSPATH)/ImageMath 3 '...
		prefix '05_Mask_RInput/Laplacian_LPBA40.nii.gz '...
		'Laplacian '...
		 LPBA40_Template_location ' 1.5 1\n']);

    % 3. Perform registration of image to template
    fprintf(fid,['\t$(ANTSPATH)/antsRegistration -d 3 -u 1 -w [0.025, 0.975] '...
	   '-o ' prefix '06_Mask_ROutput/RegistrationOutput_' ptno_Descrip_UID '_ '...
	   '-r ' prefix '05_Mask_RInput/InitialAffine_' ptno_Descrip_UID '.mat -z 1 --float 0 '...
        '-m MI[' LPBA40_Template_location ','...
	      prefix '01_N4/N4_' ptno_Descrip_UID '.nii.gz,1,32,Regular,0.25] -c [1000x500x250x100,1e-8,10] -t Rigid[0.1] -f 8x4x2x1 -s 4x2x1x0 '...
        '-m MI[' LPBA40_Template_location ','...
	      prefix '01_N4/N4_' ptno_Descrip_UID '.nii.gz,1,32,Regular,0.25] -c [1000x500x250x100,1e-8,10] -t Affine[0.1] -f 8x4x2x1 -s 4x2x1x0 '...
        '-m CC[' LPBA40_Template_location ','...
	      prefix '01_N4/N4_' ptno_Descrip_UID '.nii.gz,0.5,4] '...
        '-m CC[' prefix '05_Mask_RInput/Laplacian_LPBA40.nii.gz,'...
	      prefix '05_Mask_RInput/Laplacian_' ptno_Descrip_UID '.nii.gz,0.5,4] -c [50x10x0,1e-9,15] -t SyN[0.1,3,0] -f 4x2x1 -s 2x1x0\n']);

    % 4. Apply registration to mask
    fprintf(fid,['\t$(ANTSPATH)/antsApplyTransforms -d 3 '...
		'-i ' LPBA40_mask_location ' '...
		'-o ' prefix '07_Masks/Mask_' ptno_Descrip_UID '.nii.gz '...
		'-r ' prefix '01_N4/N4_' ptno_Descrip_UID '.nii.gz -n Gaussian '...
                '-t [' prefix '06_Mask_ROutput/RegistrationOutput_' ptno_Descrip_UID '_0GenericAffine.mat,1] '...
		'-t ' prefix '06_Mask_ROutput/RegistrationOutput_' ptno_Descrip_UID '_1InverseWarp.nii.gz --float 0\n']);

    % 5. Treshold and Get largest component of mask. 
    fprintf(fid,['\t$(ANTSPATH)/ThresholdImage 3 '...
		prefix '07_Masks/Mask_' ptno_Descrip_UID '.nii.gz '...
		prefix '07_Masks/Mask_thresholded_' ptno_Descrip_UID '.nii.gz 0.5 1 1 0\n']); % Threshold Mask
    fprintf(fid,['\t$(ANTSPATH)/ImageMath 3 '...
		prefix '07_Masks/Mask_LC_' ptno_Descrip_UID '.nii.gz '...
		'GetLargestComponent '...
		prefix '07_Masks/Mask_thresholded_' ptno_Descrip_UID '.nii.gz\n']); % Get largest component of mask 

    fprintf(fid,['\t$(ANTSPATH)/ImageMath 3 '...
		prefix '07_Masks/Mask_MD_' ptno_Descrip_UID '.nii.gz '...
		'MD '...
		prefix '07_Masks/Mask_LC_' ptno_Descrip_UID '.nii.gz ' num2str(MD_parameter) '\n']); % Dilate mask
    fprintf(fid,['\t$(ANTSPATH)/ImageMath 3 '...
		prefix '07_Masks/Mask_MC_' ptno_Descrip_UID '.nii.gz '...
		'MC '...
		prefix '07_Masks/Mask_MD_' ptno_Descrip_UID '.nii.gz ' num2str(MC_parameter) '\n']); % Close mask
    
    % 6. Perform Atropos segmentation to get WM, GM, and CSF. Combine these masks.
    fprintf(fid,['\t$(ANTSPATH)/Atropos -d 3 '...
		'-o ' prefix '07_Masks/Atropos_Mask_' ptno_Descrip_UID '.nii.gz '...
		'-a ' prefix '01_N4/N4_' ptno_Descrip_UID '.nii.gz '...
		'-x ' prefix '07_Masks/Mask_MC_' ptno_Descrip_UID '.nii.gz '...
        	'-i kmeans[3] -c [3, 0.0] -m [0.1, 1x1x1] -k Gaussian\n']);

    % 7. Separate WM, GM, CSF masks
    fprintf(fid,['\t$(ANTSPATH)/ThresholdImage 3 '...
		prefix '07_Masks/Atropos_Mask_' ptno_Descrip_UID '.nii.gz '...
		prefix '07_Masks/Atropos_WM_' ptno_Descrip_UID '.nii.gz 3 3 1 0\n']);
    fprintf(fid,['\t$(ANTSPATH)/ThresholdImage 3 '...
		prefix '07_Masks/Atropos_Mask_' ptno_Descrip_UID '.nii.gz '...
		prefix '07_Masks/Atropos_GM_' ptno_Descrip_UID '.nii.gz 2 2 1 0\n']);
    fprintf(fid,['\t$(ANTSPATH)/ThresholdImage 3 '...
		prefix '07_Masks/Atropos_Mask_' ptno_Descrip_UID '.nii.gz '...
		prefix '07_Masks/Atropos_CSF_' ptno_Descrip_UID '.nii.gz 1 1 1 0\n']);

    % 8. Combine WM, GM, CSF masks into 1
    fprintf(fid,['\t$(ANTSPATH)/ImageMath 3 '...
		prefix '07_Masks/Atropos_WM_GM_' ptno_Descrip_UID '.nii.gz '...
		'addtozero '...
		prefix '07_Masks/Atropos_WM_' ptno_Descrip_UID '.nii.gz '...
		prefix '07_Masks/Atropos_GM_' ptno_Descrip_UID '.nii.gz\n']);
    fprintf(fid,['\t$(ANTSPATH)/ImageMath 3 '...
		prefix '07_Masks/Atropos_WM_GM_CSF_' ptno_Descrip_UID '.nii.gz '...
		'addtozero '...
		prefix '07_Masks/Atropos_WM_GM_' ptno_Descrip_UID '.nii.gz '...
		prefix '07_Masks/Atropos_CSF_' ptno_Descrip_UID '.nii.gz\n']);
    fprintf(fid,['\t$(ANTSPATH)/ImageMath 3 '...
		prefix '07_Masks/Atropos_LC_' ptno_Descrip_UID '.nii.gz '...
		'GetLargestComponent '...
		prefix '07_Masks/Atropos_WM_GM_CSF_' ptno_Descrip_UID '.nii.gz\n']);

end
fclose(fid);
system(['make -j ' num2str(n_cores) ' -f ' prefix makefile])

end


