% load_sql
cd('/mnt/data/scratch/igilab/jslin1/RadPath')
path(path, '/mnt/data/scratch/igilab/jslin1/Matlab_add-ons/mksqlite-1.14')
path(path, '/mnt/data/scratch/igilab/jslin1/Matlab_add-ons/NIfTI_20140122')
path(path, '/mnt/data/scratch/igilab/jslin1/RadPath/Functions')
path(path, '/mnt/data/scratch/igilab/jslin1/RadPath/Functions/mrn_to_ptno')
script01_prefix = 'Script01_T1_T2_SWAN/';
script02_prefix = 'Script02_DWI_DTI/';
script03_prefix = 'Script03_DCE_DSC/';
script04_prefix = 'Script04_VOI/';

mksqlite('open', 'ctkDICOM.sql' );
studies_all = mksqlite(['select * from Studies order by StudyDate ASC']);
series_all = mksqlite(['select * from Series order by SeriesDate, SeriesInstanceUID ASC']);
    
series_T2 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%T2%'' '... % Includes T2, T2star, T2FLAIR
    'and SeriesDescription not like ''%*%'' '... % Exclude T2star
    'and SeriesDescription not like ''%FLAIR%'' '... % Exclude T2 FLAIR
    'order by SeriesDate ASC']);
series_T2_register = series_T2([2:8 10:size(series_T2,1)]); % Ptno 1, 7 - High rez T2+C
series_T2_HistMatch = series_T2([1 3:7 9:size(series_T2,1)]); % Ptno 1, 7 - lower rez T2

%% T1,T2 SWAN divisions
series_T1_T2_SWAN = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%T1%'' '... % Includes T1, T1post
    'or SeriesDescription like ''%T2%'' '... % Includes T2, T2star, T2FLAIR
    'or SeriesDescription like ''%SWAN%'' '... % Includes SWAN Image volume
    'order by SeriesDate ASC']);
    
series_T1 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%T1%'' '...
    'and SeriesDescription not like ''%STEALTH%'' '...
    'and SeriesDescription not like ''%+C%'' '...
    'order by SeriesDate ASC']); %17
series_T1post = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%T1%'' '... % Includes T1, T1post
    'and (SeriesDescription like ''%STEALTH%'' '... %Includes only post
    'or SeriesDescription like ''%+C%'') '... % Includes only post
    'order by SeriesDate ASC']);
series_T2star = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%T2*%'' '... % Includes T2star
    'order by SeriesDate ASC']);
series_T2FLAIR = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%FLAIR%'' '... % Includes T2FLAIR
    'order by SeriesDate ASC']);
series_SWAN = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%SWAN%'' '... % Includes SWAN
    'order by SeriesDate ASC']);
  
%% DWI/DTI divisons
series_ADC = mksqlite(['select studies.StudyDate, Series.* from Series inner join Studies on Series.StudyInstanceUID = Studies.StudyInstanceUID where '...
        'Series.SeriesDescription like ''%Apparent Diffusion Coefficient%'' '... % Includes ADC and eADC
        'and Series.SeriesDescription not like ''%Exponential%'' '... % Excludes eADC
        'order by Studies.StudyDate ASC']);  
series_eADC = mksqlite(['select studies.StudyDate, Series.* from Series inner join Studies on Series.StudyInstanceUID = Studies.StudyInstanceUID where '...
        'Series.SeriesDescription like ''%Exponential Apparent Diffusion Coefficient%'' '... % Includes eADC
        'order by Studies.StudyDate ASC']);  
series_FA = mksqlite(['select studies.StudyDate, Series.* from Series inner join Studies on Series.StudyInstanceUID = Studies.StudyInstanceUID where '...
        'Series.SeriesDescription like ''%Fractional Aniso%'' '... % Includes FA
        'order by Studies.StudyDate ASC']);  
series_AvgDC = mksqlite(['select studies.StudyDate, Series.* from Series inner join Studies on Series.StudyInstanceUID = Studies.StudyInstanceUID where '...
        'Series.SeriesDescription like ''%Average DC%'' '...  % Includes AvgDC
        'order by Studies.StudyDate ASC']);   

series_ADC_eADC = mksqlite(['select studies.StudyDate, Series.* from Series inner join Studies on Series.StudyInstanceUID = Studies.StudyInstanceUID where '...
        'Series.SeriesDescription like ''%Apparent Diffusion Coefficient%'' '... % Includes ADC and eADC from DWI
        'order by Studies.StudyDate ASC']); 
series_AvgDC_FA = mksqlite(['select studies.StudyDate, Series.* from Series inner join Studies on Series.StudyInstanceUID = Studies.StudyInstanceUID where '...
       'Series.SeriesDescription like ''%Average DC%'' '...  % Includes ADC from DTI
       'or Series.SeriesDescription like ''%Fractional Aniso%'' '... % Includes FA
       'order by Studies.StudyDate ASC']);

series_diffmaps_alone = mksqlite(['select * from Series where '...
        'SeriesDescription like ''%Apparent Diffusion Coefficient%'' '... % Includes ADC and eADC from DWI
        'or SeriesDescription like ''%Fractional Aniso%'' '... % Includes FA from DTI
        'or SeriesDescription like ''%Average DC%'' '...  % Includes ADC from DTI
        'order by SeriesDate ASC']);
%% DCE/DSC combos
series_DCE_DSC = mksqlite(['select * from Series '...
    'where SeriesDescription like ''%DCE%'' '...
    'or SeriesDescription like ''%DSC%'' '...
    'order by SeriesDate, SeriesInstanceUID ASC']);

series_DCE_DSC_plusmaps = mksqlite(['select * from Series where '...
        'SeriesDescription like ''%DCE%'' '...
        'or SeriesDescription like ''%DSC%'' '...
        'or SeriesDescription like ''%rBV%'' '...
        'or SeriesDescription like ''%rBF%'' '...
        'or SeriesDescription like ''%MTT%'' '...
        'or SeriesDescription like ''%Delay%'' '...
        'or SeriesDescription like ''%Leakage (K2)%'' '...
        'or SeriesDescription like ''%K12%'' '...
        'or SeriesDescription like ''%K21%'' '...
        'or SeriesDescription like ''%Vp%'' '...
        'or SeriesDescription like ''%Ve (distribution volume)%'' '...
        'or SeriesDescription like ''%Wash-in%'' '...
        'or SeriesDescription like ''%Wash-out%'' '...
        'or SeriesDescription like ''%Time to peak%'' '...
        'or SeriesDescription like ''%Area under curve%'' '...
        'or SeriesDescription like ''%Peak enhancement%'' '...
        'order by SeriesDate, SeriesInstanceUID ASC']);
%DSC
series_DSC = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%DSC%'' '...
    'order by SeriesDate, SeriesInstanceUID ASC']);
series_DSC_maps = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%rBV%'' '...
    'or SeriesDescription like ''%rBF%'' '...
    'or SeriesDescription like ''%MTT%'' '...
    'or SeriesDescription like ''%Delay%'' '...
    'or SeriesDescription like ''%Leakage (K2)%'' '...
    'order by SeriesDate, SeriesInstanceUID ASC']);
series_DSC_plusmaps = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%DSC%'' '...
    'or SeriesDescription like ''%rBV%'' '...
    'or SeriesDescription like ''%rBF%'' '...
    'or SeriesDescription like ''%MTT%'' '...
    'or SeriesDescription like ''%Delay%'' '...
    'or SeriesDescription like ''%Leakage (K2)%'' '...
    'order by SeriesDate, SeriesInstanceUID ASC']);
%DCE
series_DCE = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%DCE%'' '...
    'order by SeriesDate, SeriesInstanceUID ASC']);
series_DCE_maps =     mksqlite(['select * from Series where '...
    'SeriesDescription like ''%K12%'' '...
    'or SeriesDescription like ''%K21%'' '...
    'or SeriesDescription like ''%Vp%'' '...
    'or SeriesDescription like ''%Ve (distribution volume)%'' '...
    'or SeriesDescription like ''%Wash-in%'' '...
    'or SeriesDescription like ''%Wash-out%'' '...
    'or SeriesDescription like ''%Time to peak%'' '...
    'or SeriesDescription like ''%Area under curve%'' '...
    'or SeriesDescription like ''%Peak enhancement%'' '...
    'order by SeriesDate, SeriesInstanceUID ASC']);
series_DCE_plusmaps =     mksqlite(['select * from Series where '...
    'SeriesDescription like ''%DCE%'' '...
    'or SeriesDescription like ''%K12%'' '...
    'or SeriesDescription like ''%K21%'' '...
    'or SeriesDescription like ''%Vp%'' '...
    'or SeriesDescription like ''%Ve (distribution volume)%'' '...
    'or SeriesDescription like ''%Wash-in%'' '...
    'or SeriesDescription like ''%Wash-out%'' '...
    'or SeriesDescription like ''%Time to peak%'' '...
    'or SeriesDescription like ''%Area under curve%'' '...
    'or SeriesDescription like ''%Peak enhancement%'' '...
    'order by SeriesDate, SeriesInstanceUID ASC']);

%% DSC
series_rBV = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%rBV%'' '... % Includes rBV and rBV_corr
    'and SeriesDescription like ''%not%'' '... % Includes rBV
    'order by SeriesDate ASC']);
series_rBV_corr = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%rBV%'' '... % Includes rBV and rBV_corr
    'and SeriesDescription not like ''%not%'' '... % Excludes rBV
    'order by SeriesDate ASC']);
series_rBF = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%rBF%'' '... % Includes rBF 
    'order by SeriesDate ASC']);
series_MTT = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%MTT%'' '... % Includes MTT
    'order by SeriesDate ASC']);
series_Delay = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Delay%'' '... % Includes Delay
    'order by SeriesDate ASC']);
series_K2 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Leakage (K2)%'' '... % Includes K2
    'order by SeriesDate ASC']);

%% DCE
series_Ktrans = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%K12%'' '... % Includes Ktrans
    'order by SeriesDate ASC,SeriesDescription DESC']);
series_Kep = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%K21%'' '... % Includes Kep
    'order by SeriesDate ASC,SeriesDescription DESC']);
series_Vp = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Vp%'' '... % Includes Vp
    'order by SeriesDate ASC,SeriesDescription DESC']);
series_Ve = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Ve (distribution volume)%'' '... % Includes Ve
    'order by SeriesDate ASC,SeriesDescription DESC']);
series_Wash_in = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Wash-in%'' '... % Includes Wash-in
    'order by SeriesDate ASC,SeriesDescription DESC']);
series_Wash_out = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Wash-out%'' '... % Includes Wash-out
    'order by SeriesDate ASC,SeriesDescription DESC']);
series_TTP = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Time to peak%'' '... % Includes TTP
    'order by SeriesDate ASC,SeriesDescription DESC']);
series_AUC = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Area under curve%'' '... % Includes AUC
    'order by SeriesDate ASC,SeriesDescription DESC']);
series_Peak = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Peak enhancement%'' '... % Includes Peak enhancement
    'order by SeriesDate ASC,SeriesDescription DESC']);

%% DCE stratified x 4
% 1/9
series_Ktrans1 = mksqlite(['select * from Series where '... % 1/9
    'SeriesDescription like ''%K12%'' '... 
    'and SeriesDescription like ''%SSS delSI%'' '... 
    'order by SeriesDate ASC']);
series_Ktrans2 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%K12%'' '... 
    'and SeriesDescription like ''%SSS R1%'' '... 
    'order by SeriesDate ASC']);
series_Ktrans3 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%K12%'' '... 
    'and SeriesDescription like ''%MCA delSI%'' '... 
    'order by SeriesDate ASC']);
series_Ktrans4 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%K12%'' '...              % Includes Ktrans
    'and SeriesDescription like ''%MCA R1%'' '... 
    'order by SeriesDate ASC']);
%%
series_Kep1 = mksqlite(['select * from Series where '... % 2/9
    'SeriesDescription like ''%K21%'' '... 
    'and SeriesDescription like ''%SSS delSI%'' '... 
    'order by SeriesDate ASC']);
series_Kep2 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%K21%'' '... 
    'and SeriesDescription like ''%SSS R1%'' '... 
    'order by SeriesDate ASC']);
series_Kep3 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%K21%'' '... 
    'and SeriesDescription like ''%MCA delSI%'' '... 
    'order by SeriesDate ASC']);
series_Kep4 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%K21%'' '...               % Includes Kep
    'and SeriesDescription like ''%MCA R1%'' '... 
    'order by SeriesDate ASC']);
%%
series_Vp1 = mksqlite(['select * from Series where '...     % 3/9
    'SeriesDescription like ''%Vp%'' '... 
    'and SeriesDescription like ''%SSS delSI%'' '... 
    'order by SeriesDate ASC']);
series_Vp2 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Vp%'' '... 
    'and SeriesDescription like ''%SSS R1%'' '... 
    'order by SeriesDate ASC']);
series_Vp3 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Vp%'' '... 
    'and SeriesDescription like ''%MCA delSI%'' '... 
    'order by SeriesDate ASC']);
series_Vp4 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Vp%'' '...                   % Includes Vp
    'and SeriesDescription like ''%MCA R1%'' '... 
    'order by SeriesDate ASC']);
%%
series_Ve1 = mksqlite(['select * from Series where '... % 4/9
    'SeriesDescription like ''%Ve (distribution volume)%'' '... 
    'and SeriesDescription like ''%SSS delSI%'' '... 
    'order by SeriesDate ASC']);
series_Ve2 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Ve (distribution volume)%'' '... 
    'and SeriesDescription like ''%SSS R1%'' '... 
    'order by SeriesDate ASC']);
series_Ve3 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Ve (distribution volume)%'' '... 
    'and SeriesDescription like ''%MCA delSI%'' '... 
    'order by SeriesDate ASC']);
series_Ve4 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Ve (distribution volume)%'' '... % Includes Ve
    'and SeriesDescription like ''%MCA R1%'' '... 
    'order by SeriesDate ASC']);
%% 
series_Wash_in1 = mksqlite(['select * from Series where '... % 5/9
    'SeriesDescription like ''%Wash-in%'' '... 
    'and SeriesDescription like ''%SSS delSI%'' '... 
    'order by SeriesDate ASC']);
series_Wash_in2 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Wash-in%'' '... 
    'and SeriesDescription like ''%SSS R1%'' '... 
    'order by SeriesDate ASC']);
series_Wash_in3 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Wash-in%'' '... 
    'and SeriesDescription like ''%MCA delSI%'' '... 
    'order by SeriesDate ASC']);
series_Wash_in4 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Wash-in%'' '...                  % Includes wash-in
    'and SeriesDescription like ''%MCA R1%'' '... 
    'order by SeriesDate ASC']);
%% 
series_Wash_out1 = mksqlite(['select * from Series where '... % 6/9
    'SeriesDescription like ''%Wash-out%'' '... 
    'and SeriesDescription like ''%SSS delSI%'' '... 
    'order by SeriesDate ASC']);
series_Wash_out2 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Wash-out%'' '... 
    'and SeriesDescription like ''%SSS R1%'' '... 
    'order by SeriesDate ASC']);
series_Wash_out3 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Wash-out%'' '... 
    'and SeriesDescription like ''%MCA delSI%'' '... 
    'order by SeriesDate ASC']);
series_Wash_out4 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Wash-out%'' '...          % Includes Wash-out
    'and SeriesDescription like ''%MCA R1%'' '... 
    'order by SeriesDate ASC']);
%%
series_TTP1 = mksqlite(['select * from Series where '... % 7/9
    'SeriesDescription like ''%Time to peak%'' '... 
    'and SeriesDescription like ''%SSS delSI%'' '... 
    'order by SeriesDate ASC']);
series_TTP2 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Time to peak%'' '... 
    'and SeriesDescription like ''%SSS R1%'' '... 
    'order by SeriesDate ASC']);
series_TTP3 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Time to peak%'' '... 
    'and SeriesDescription like ''%MCA delSI%'' '... 
    'order by SeriesDate ASC']);
series_TTP4 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Time to peak%'' '...         % Includes TTP
    'and SeriesDescription like ''%MCA R1%'' '... 
    'order by SeriesDate ASC']);
%%
series_AUC1 = mksqlite(['select * from Series where '... % 8/9
    'SeriesDescription like ''%Area under curve%'' '... 
    'and SeriesDescription like ''%SSS delSI%'' '... 
    'order by SeriesDate ASC']);
series_AUC2 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Area under curve%'' '... 
    'and SeriesDescription like ''%SSS R1%'' '... 
    'order by SeriesDate ASC']);
series_AUC3 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Area under curve%'' '... 
    'and SeriesDescription like ''%MCA delSI%'' '... 
    'order by SeriesDate ASC']);
series_AUC4 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Area under curve%'' '...         % Includes AUC
    'and SeriesDescription like ''%MCA R1%'' '... 
    'order by SeriesDate ASC']);
%%
series_Peak1 = mksqlite(['select * from Series where '... % 9/9
    'SeriesDescription like ''%Peak enhancement%'' '... 
    'and SeriesDescription like ''%SSS delSI%'' '... 
    'order by SeriesDate ASC']);
series_Peak2 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Peak enhancement%'' '... 
    'and SeriesDescription like ''%SSS R1%'' '... 
    'order by SeriesDate ASC']);
series_Peak3 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Peak enhancement%'' '... 
    'and SeriesDescription like ''%MCA delSI%'' '... 
    'order by SeriesDate ASC']);
series_Peak4 = mksqlite(['select * from Series where '...
    'SeriesDescription like ''%Peak enhancement%'' '...     % Includes Peak
    'and SeriesDescription like ''%MCA R1%'' '... 
    'order by SeriesDate ASC']);
